sudo: false
language: python

# don't clone the whole repo history, one commit will do
git:
  depth: 1

# only build branches we care about (PRs are built seperately)
#branches:
#  only:
#    - master
#    - develop
#    - /^release-v.*/

env:
  - XDG_CACHE_DIR=/cache

cache:
  directories:
    - /cache

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: TOX_ENV=py27
    
install:
  - pip install tox

script:
  - find $HOME/.cache/pip
  - tox -ve $TOX_ENV | gawk '{ print strftime("[%Y-%m-%d %H:%M:%S]"), $0 }'

  # clean out old http files from the cache (there's no reason to believe they
  # will be quicker to download from S3 than from pypi, so there's not much
  # point caching them.)
  #
  # (this doesn't appear to work when placed in `before_cache`, despite that
  # being `before_cache`'s stated purpose :/
  - rm -vr $HOME/.cache/pip/http
  - find $HOME/.cache/pip
