sudo: false
language: python

# don't clone the whole repo history, one commit will do
git:
  depth: 1

# only build branches we care about (PRs are built seperately)
#branches:
#  only:
#    - master
#    - develop
#    - /^release-v.*/

cache:
  directories:
    - $HOME/cache

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env:
      - TOX_ENV=py27
      - XDG_CACHE_HOME=$HOME/cache
   
install:
  - pip install tox

script:
  - find $HOME/cache/pip
  - tox -vve $TOX_ENV
  - find $HOME/cache/pip
