sudo: false
language: python

# tell travis to cache ~/.cache/pip
cache: pip

# don't clone the whole repo history, one commit will do
git:
  depth: 1

# only build branches we care about (PRs are built seperately)
#branches:
#  only:
#    - master
#    - develop
#    - /^release-v.*/

# tell travis to cache ~/.cache/pip
cache: pip

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: TOX_ENV=py27
    
install:
  - pip install tox

script:
  - tox -ve $TOX_ENV | gawk '{ print strftime("[%Y-%m-%d %H:%M:%S]"), $0 }'
