version: 2
jobs:
  sytestpy2:
    docker:
      - image: richvdh/sytest-synapsepy2:20181016_00
    steps:
      - checkout:
          path: /src
      - run: /synapse_sytest.sh
      - store_artifacts:
          path: /logs
          destination: logs
      - store_test_results:
          path: /logs
workflows:
  version: 2
  build:
    jobs:
      - sytestpy2
