version: 2
jobs:
  sytestpy2:
    docker:
      image: richvdh/sytest-synapsepy2:20181016_00
    steps:
      - checkout
      - store_test_results:
          path: ~/project/logs
workflows:
  version: 2
  build:
    jobs:
      - sytestpy2
